# -*- coding: utf-8 -*-
"""email_spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4Q-JHcg2c-3-3GyGA-MeokfgkTjfXLt
"""

import pandas as pd
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/spam.csv", encoding='latin-1', header=None, names=['label', 'message', 'v1', 'v2', 'v3'])
def preprocess_text(text):
    text = text.lower()
    text = re.sub(f"[{string.punctuation}]", "", text)
    text = re.sub("\d+", "", text)
    return text

df['message'] = df['message'].apply(preprocess_text)

df['label'] = df['label'].map({'ham': 0, 'spam': 1})

df.dropna(subset=['label'], inplace=True)
print(df.head())
X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'], test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))